-- 게시글 (10개)

insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Donec quis orci eget orci vehicula condimentum.', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Puce', 'Cammie', 'Natty', '2022-08-07 19:07:13', '2022-06-06 05:52:33');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Yellow', 'Devina', 'Jolee', '2022-05-21 05:03:29', '2022-12-27 10:10:20');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Donec semper sapien a libero.', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Goldenrod', 'Jamison', 'Giordano', '2022-08-03 02:11:43', '2022-10-20 20:43:50');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('In hac habitasse platea dictumst.', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', null, 'Putnam', 'Honoria', '2022-06-20 08:05:03', '2022-09-07 08:55:22');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Nulla facilisi.', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Blue', 'Joshuah', 'Rossy', '2023-01-18 14:58:16', '2022-08-23 16:19:43');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Aquamarine', 'Dalenna', 'Leone', '2022-12-08 18:27:09', '2022-11-14 10:46:36');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', null, 'Miof mela', 'Kerk', '2022-09-26 08:49:58', '2023-04-22 14:14:07');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Phasellus id sapien in sapien iaculis congue.', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 'Red', 'Carolina', 'Jonell', '2022-10-07 00:59:55', '2023-04-06 22:34:33');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Morbi vel lectus in quam fringilla rhoncus.', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', null, 'Pammy', 'Ermanno', '2022-06-30 13:33:30', '2022-06-29 20:33:20');
insert into article (title, content, hashtag, created_by, modified_by, created_at, modified_at) values ('Vestibulum rutrum rutrum neque.', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Indigo', 'Constancy', 'Dulsea', '2023-03-15 04:30:02', '2022-08-09 05:35:37');

-- 댓글 (10개)

insert into article_comment (article_id, content, created_at, modified_at, created_by, modified_by) values (1, 'Nunc nisl.', '2022-09-07 15:13:23', '2023-01-04 23:34:55', 'Aldridge', 'Cary');
insert into article_comment (article_id, content, created_at, modified_at, created_by, modified_by) values (2, 'Nam tristique tortor eu pede.', '2022-08-03 09:59:56', '2023-02-02 00:59:56', 'Cecilio', 'Cesar');
insert into article_comment (article_id, content, created_at, modified_at, created_by, modified_by) values (3, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2023-01-18 21:42:07', '2022-10-08 22:00:42', 'Heather', 'Archer');
insert into article_comment (article_id, content, created_at, modified_at, created_by, modified_by) values (4, 'Aliquam erat volutpat.', '2022-07-15 13:16:28', '2023-01-15 23:50:04', 'Jamil', 'Katee');
insert into article_comment (article_id, content, created_at, modified_at, created_by, modified_by) values (5, 'Cras non velit nec nisi vulputate nonummy.', '2022-12-02 09:24:29', '2022-06-13 03:57:55', 'Gothart', 'Keslie');
insert into article_comment (article_id, content, created_at, modified_at, created_by, modified_by) values (6, 'Praesent blandit lacinia erat.', '2023-02-14 18:24:15', '2022-05-29 18:23:20', 'Herbert', 'Celestina');
insert into article_comment (article_id, content, created_at, modified_at, created_by, modified_by) values (7, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', '2023-03-10 05:02:54', '2023-01-18 04:00:14', 'Danell', 'Kendrick');
insert into article_comment (article_id, content, created_at, modified_at, created_by, modified_by) values (8, 'Duis bibendum.', '2022-09-23 17:23:21', '2023-03-10 21:48:15', 'Jourdain', 'Murielle');
insert into article_comment (article_id, content, created_at, modified_at, created_by, modified_by) values (9, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2023-04-10 19:20:09', '2022-08-25 00:17:28', 'Dom', 'Susette');
insert into article_comment (article_id, content, created_at, modified_at, created_by, modified_by) values (10, 'Aliquam non mauris.', '2022-11-27 03:24:08', '2023-01-22 22:35:30', 'Skelly', 'Kimberlyn');
